spring:
  profiles:
    active: dev
  # http://blog.csdn.net/BeauXie/article/details/78552919
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

